import type { Challenge } from "../types";

export const challenges: Challenge[] = [
  {
    id: "clickbait-1",
    category: "clickbait",
    visual: "none",
    question: {
      en: "Which headline is designed to provoke an emotional reaction before informing you?",
      es: "¿Cuál titular está diseñado para provocar una reacción emocional antes de informarte?",
    },
    options: [
      {
        id: "a",
        label: {
          en: "SHOCKING discovery doctors do not want you to know!",
          es: "¡Descubrimiento IMPACTANTE que los médicos no quieren que sepas!",
        },
      },
      {
        id: "b",
        label: {
          en: "Preliminary university study examines a possible new treatment.",
          es: "Un estudio universitario preliminar examina un posible nuevo tratamiento.",
        },
      },
    ],
    correctOptionId: "a",
    explanation: {
      en: "Strong emotional language, excessive capitalization and hidden sources are signals that should make you verify before sharing.",
      es: "El lenguaje emocional fuerte, las mayúsculas excesivas y las fuentes ocultas son señales que deberían llevarte a verificar antes de compartir.",
    },
    takeaway: {
      en: "Pause when a headline shouts at you — check the source before you react.",
      es: "Pausa cuando un titular te grita: verifica la fuente antes de reaccionar.",
    },
  },
  {
    id: "sources-1",
    category: "sources",
    visual: "none",
    question: {
      en: "Which post gives you more information to verify its claim?",
      es: "¿Cuál publicación te da más información para verificar su afirmación?",
    },
    options: [
      {
        id: "a",
        label: {
          en: "Scientists confirmed this yesterday. Share immediately.",
          es: "Los científicos lo confirmaron ayer. Comparte de inmediato.",
        },
      },
      {
        id: "b",
        label: {
          en: "A preliminary report published by Oxford researchers on July 18 describes the study and its limitations.",
          es: "Un informe preliminar publicado por investigadores de Oxford el 18 de julio describe el estudio y sus limitaciones.",
        },
      },
    ],
    correctOptionId: "b",
    explanation: {
      en: "Reliable information should make it possible to identify the source, date, author and original evidence.",
      es: "La información confiable debería permitir identificar la fuente, la fecha, el autor y la evidencia original.",
    },
    takeaway: {
      en: "Look for who, when, and where — vague claims deserve skepticism.",
      es: "Busca quién, cuándo y dónde: las afirmaciones vagas merecen escepticismo.",
    },
  },
  {
    id: "visual-1",
    category: "visual-context",
    visual: "social-posts",
    question: {
      en: "What should you check before assuming this image belongs to the reported event?",
      es: "¿Qué deberías comprobar antes de asumir que esta imagen pertenece al evento reportado?",
    },
    options: [
      {
        id: "a",
        label: { en: "Number of likes", es: "Número de me gusta" },
      },
      {
        id: "b",
        label: {
          en: "Original date and source",
          es: "Fecha y fuente originales",
        },
      },
      {
        id: "c",
        label: { en: "Image resolution", es: "Resolución de la imagen" },
      },
      {
        id: "d",
        label: { en: "Caption length", es: "Longitud del pie de foto" },
      },
    ],
    correctOptionId: "b",
    explanation: {
      en: "Real images are often reused with false dates, locations or descriptions.",
      es: "Las imágenes reales a menudo se reutilizan con fechas, lugares o descripciones falsas.",
    },
    takeaway: {
      en: "Reverse-check the image: original date and source before you trust the caption.",
      es: "Verifica la imagen: fecha y fuente originales antes de confiar en el pie de foto.",
    },
  },
  {
    id: "ai-1",
    category: "ai-content",
    visual: "ai-grid",
    question: {
      en: "Which response is the most responsible when an image looks unusual?",
      es: "¿Cuál es la respuesta más responsable cuando una imagen se ve inusual?",
    },
    options: [
      {
        id: "a",
        label: {
          en: "It is definitely generated by AI.",
          es: "Definitivamente fue generada por IA.",
        },
      },
      {
        id: "b",
        label: {
          en: "It is definitely authentic.",
          es: "Definitivamente es auténtica.",
        },
      },
      {
        id: "c",
        label: {
          en: "Visual anomalies are a warning, but the source and context must also be checked.",
          es: "Las anomalías visuales son una advertencia, pero también hay que verificar la fuente y el contexto.",
        },
      },
      {
        id: "d",
        label: {
          en: "Share it and let others decide.",
          es: "Compártela y deja que otros decidan.",
        },
      },
    ],
    correctOptionId: "c",
    explanation: {
      en: "No single visual artifact proves that an image was generated by AI. Verification requires source, context and additional evidence.",
      es: "Ningún artefacto visual por sí solo prueba que una imagen fue generada por IA. La verificación requiere fuente, contexto y evidencia adicional.",
    },
    takeaway: {
      en: "Treat unusual visuals as a prompt to investigate — not as proof by themselves.",
      es: "Trata lo visual inusual como una señal para investigar, no como prueba por sí sola.",
    },
  },
  {
    id: "emotion-1",
    category: "emotional-manipulation",
    visual: "emotion-cards",
    question: {
      en: "Which element is trying to pressure the reader into acting without verification?",
      es: "¿Qué elemento intenta presionar al lector para actuar sin verificar?",
    },
    options: [
      {
        id: "a",
        label: {
          en: "A calm summary with a link to the original study",
          es: "Un resumen calmado con enlace al estudio original",
        },
      },
      {
        id: "b",
        label: {
          en: "“ACT NOW or you will lose everything — share before it is deleted!”",
          es: "“¡ACTÚA YA o lo perderás todo — comparte antes de que lo borren!”",
        },
      },
      {
        id: "c",
        label: {
          en: "A dated press release from a known institution",
          es: "Un comunicado de prensa con fecha de una institución conocida",
        },
      },
      {
        id: "d",
        label: {
          en: "A neutral headline describing preliminary findings",
          es: "Un titular neutral que describe hallazgos preliminares",
        },
      },
    ],
    correctOptionId: "b",
    explanation: {
      en: "Artificial urgency, fear, absolute language and demands to share immediately are designed to bypass critical thinking.",
      es: "La urgencia artificial, el miedo, el lenguaje absoluto y las peticiones de compartir de inmediato buscan saltarse el pensamiento crítico.",
    },
    takeaway: {
      en: "If a message rushes you with fear or absolutes, slow down and verify first.",
      es: "Si un mensaje te apresura con miedo o absolutos, reduce la velocidad y verifica primero.",
    },
  },
  {
    id: "stats-1",
    category: "misleading-stats",
    visual: "truncated-chart",
    question: {
      en: "What makes this chart potentially misleading?",
      es: "¿Qué hace que este gráfico sea potencialmente engañoso?",
    },
    options: [
      {
        id: "a",
        label: {
          en: "It uses blue and teal colors",
          es: "Usa colores azul y teal",
        },
      },
      {
        id: "b",
        label: {
          en: "The vertical axis starts near the measured values, exaggerating the difference",
          es: "El eje vertical empieza cerca de los valores medidos, exagerando la diferencia",
        },
      },
      {
        id: "c",
        label: {
          en: "It shows two categories instead of ten",
          es: "Muestra dos categorías en lugar de diez",
        },
      },
      {
        id: "d",
        label: {
          en: "The bars are rounded at the top",
          es: "Las barras están redondeadas en la parte superior",
        },
      },
    ],
    correctOptionId: "b",
    explanation: {
      en: "A truncated vertical axis can make small differences look dramatic. Always check where the axis starts.",
      es: "Un eje vertical truncado puede hacer que diferencias pequeñas parezcan dramáticas. Siempre revisa dónde empieza el eje.",
    },
    takeaway: {
      en: "Read the scale — truncated axes can exaggerate change.",
      es: "Lee la escala: los ejes truncados pueden exagerar el cambio.",
    },
  },
];

export const categorySkills: Record<
  Challenge["category"],
  { en: string; es: string }
> = {
  clickbait: {
    en: "Spotting emotional headlines",
    es: "Detectar titulares emocionales",
  },
  sources: {
    en: "Checking provenance",
    es: "Verificar procedencia",
  },
  "visual-context": {
    en: "Verifying image context",
    es: "Verificar contexto de imágenes",
  },
  "ai-content": {
    en: "Responsible AI skepticism",
    es: "Escepticismo responsable ante la IA",
  },
  "emotional-manipulation": {
    en: "Resisting pressure tactics",
    es: "Resistirse a tácticas de presión",
  },
  "misleading-stats": {
    en: "Reading charts critically",
    es: "Leer gráficos con criterio",
  },
};
